/**
 * Deterministic n8n Workflow Assembler
 *
 * Converts a WorkflowIntermediate (logical layer) into a valid n8n JSON file.
 * The AI never writes raw n8n JSON — this function is the single source of
 * schema-compliant output.
 *
 * Runs client-side only. No server round-trip needed.
 */

import type { WorkflowIntermediate, N8nIntermediateNode } from '../types';
import { N8N_NODE_TEMPLATES } from '../data/n8nNodeTemplates';

function generateUUID(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

interface AssembledNode {
  id: string;
  name: string;
  type: string;
  typeVersion: number;
  position: [number, number];
  parameters: Record<string, unknown>;
  credentials?: Record<string, { id: string; name: string }>;
}

function buildStickyNoteContent(intermediate: WorkflowIntermediate): string {
  const allRequirements: string[] = [];
  for (const node of intermediate.nodes) {
    for (const req of node.configRequirements) {
      if (!allRequirements.includes(req)) {
        allRequirements.push(req);
      }
    }
  }

  const reqList = allRequirements.length > 0
    ? allRequirements.map(r => `   • ${r}`).join('\n')
    : '   • No external credentials required';

  const now = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  return `🔧 SETUP REQUIRED — ${intermediate.workflowName}

Generated by OXYGY AI Upskilling Platform. Before activating this workflow:

1. Connect your credentials:
${reqList}

2. Test with sample data before activating

3. Review AI node prompts — edit the system prompt to match your specific use case

Generated on ${now}. Workflow complexity: ${intermediate.complexity}.`;
}

export function assembleN8nWorkflow(intermediate: WorkflowIntermediate): string {
  const nodes: AssembledNode[] = [];
  const nodeIds: string[] = [];

  // 1. Add sticky note at [250, 150]
  const stickyId = generateUUID();
  nodes.push({
    id: stickyId,
    name: 'Setup Instructions',
    type: 'n8n-nodes-base.stickyNote',
    typeVersion: 1,
    position: [250, 150],
    parameters: {
      content: buildStickyNoteContent(intermediate),
      width: 420,
      height: 320,
    },
  });

  // 2. Build workflow nodes
  for (let i = 0; i < intermediate.nodes.length; i++) {
    const node = intermediate.nodes[i];
    const templateMeta = N8N_NODE_TEMPLATES[node.n8nNodeKey];

    const id = generateUUID();
    nodeIds.push(id);

    const position: [number, number] = [250 + i * 250, 500];

    if (templateMeta) {
      const tpl = templateMeta.template;
      nodes.push({
        id,
        name: node.name,
        type: tpl.type,
        typeVersion: tpl.typeVersion,
        position,
        parameters: { ...tpl.parameters },
        ...(tpl.credentials ? { credentials: { ...tpl.credentials } } : {}),
      });
    } else {
      // Fallback: httpRequest node + sticky note warning
      nodes.push({
        id,
        name: node.name,
        type: 'n8n-nodes-base.httpRequest',
        typeVersion: 4.2,
        position,
        parameters: {
          method: 'GET',
          url: 'https://YOUR_API_ENDPOINT',
          options: {},
        },
      });

      // Add a warning sticky note next to the fallback node
      nodes.push({
        id: generateUUID(),
        name: `⚠ ${node.name} - Manual Setup`,
        type: 'n8n-nodes-base.stickyNote',
        typeVersion: 1,
        position: [position[0], position[1] - 180],
        parameters: {
          content: `⚠ ${node.service || node.n8nNodeKey} not in template library — configure this as an HTTP Request node or install the community node.`,
          width: 220,
          height: 120,
        },
      });
    }
  }

  // 3. Build connections (linear chain)
  const connections: Record<string, { main: Array<Array<{ node: string; type: string; index: number }>> }> = {};

  for (let i = 0; i < nodeIds.length - 1; i++) {
    const currentNode = intermediate.nodes[i];
    const currentNodeName = currentNode.name;

    if (currentNode.n8nNodeKey === 'if' || currentNode.n8nNodeKey === 'filter') {
      // For condition nodes: true branch goes to next node, false branch also goes to next
      const nextNodeName = intermediate.nodes[i + 1].name;
      connections[currentNodeName] = {
        main: [
          [{ node: nextNodeName, type: 'main', index: 0 }],
          // False branch: also connects to the next node (simple chain)
          i + 2 < nodeIds.length
            ? [{ node: intermediate.nodes[i + 2].name, type: 'main', index: 0 }]
            : [{ node: nextNodeName, type: 'main', index: 0 }],
        ],
      };
    } else {
      const nextNodeName = intermediate.nodes[i + 1].name;
      connections[currentNodeName] = {
        main: [[{ node: nextNodeName, type: 'main', index: 0 }]],
      };
    }
  }

  // 4. Assemble top-level wrapper
  const result = {
    name: intermediate.workflowName,
    nodes,
    connections,
    active: false,
    settings: { executionOrder: 'v1' },
    meta: {
      templateCredsSetupCompleted: false,
      generatedBy: 'OXYGY AI Upskilling Platform',
    },
  };

  return JSON.stringify(result, null, 2);
}

/**
 * Convert app workflow nodes to n8n WorkflowIntermediate.
 * This bridges the app's internal node system (input/processing/output layers)
 * with the n8n intermediate format.
 */
import type { WorkflowNode } from '../types';
import { NODE_MAP } from '../data/workflow-designer-content';
import { APP_NODE_TO_N8N_KEY, N8N_NODE_TEMPLATES, getN8nNodeType } from '../data/n8nNodeTemplates';

export function buildIntermediate(
  workflowName: string,
  workflowDescription: string,
  nodes: WorkflowNode[],
  richContext?: WorkflowIntermediate['context'],
): WorkflowIntermediate {
  const intermediateNodes: N8nIntermediateNode[] = nodes.map((node, i) => {
    const def = NODE_MAP[node.node_id];
    const n8nKey = APP_NODE_TO_N8N_KEY[node.node_id] || 'httpRequest';
    const templateMeta = N8N_NODE_TEMPLATES[n8nKey];
    const nodeType = getN8nNodeType(node.layer, n8nKey);

    // Build config requirements
    const configReqs: string[] = [];
    if (templateMeta?.credentialType) {
      configReqs.push(templateMeta.configLabel);
    }
    if (['claudeAi', 'openAi'].includes(n8nKey)) {
      configReqs.push('Edit system prompt');
    }
    if (n8nKey === 'httpRequest') {
      configReqs.push('Set endpoint URL');
      configReqs.push('Add authentication header');
    }

    return {
      id: `node_${i + 1}`,
      name: node.name,
      type: nodeType,
      service: templateMeta?.service || def?.name || null,
      n8nNodeKey: n8nKey,
      description: node.custom_description || def?.description || '',
      configRequirements: configReqs,
    };
  });

  // Determine complexity
  const nodeCount = nodes.length;
  const complexity: WorkflowIntermediate['complexity'] =
    nodeCount <= 3 ? 'simple' : nodeCount <= 6 ? 'moderate' : 'complex';

  // Estimate run time
  const hasAi = nodes.some(n => ['proc-ai-agent', 'proc-ai-loop', 'proc-sentiment', 'proc-classifier', 'proc-summarizer', 'proc-translate'].includes(n.node_id));
  const hasLoop = nodes.some(n => n.node_id === 'proc-ai-loop');
  const estimatedRunTime = hasLoop ? '30–120 seconds' : hasAi ? '5–15 seconds' : '1–5 seconds';

  // Human in the loop check
  const humanInTheLoop = nodes.some(n => n.node_id === 'proc-human-review');

  return {
    workflowName,
    summary: workflowDescription,
    complexity,
    estimatedRunTime,
    humanInTheLoop,
    nodes: intermediateNodes,
    ...(richContext ? { context: richContext } : {}),
  };
}